/*
 * Copyright 2021 Christopher Sieh (stelzo@steado.de)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

INSERT INTO "public"."branch"("id", "name") VALUES(1, 'main') RETURNING "id", "name";

INSERT INTO "public"."multilingualentity"("id","name_de","name_en","name_es","name_fr","name_it","name_pt")
VALUES
('1',E'AP',E'AP',E'PA',E'PA',E'PA',E'PA'),
('2',E'BP',E'MP',E'PM',E'PM',E'PM',E'PM'),
('3',E'RW',E'Range',E'alcance',E'Portée',E'Portata',E'de alcance'),
('4',E'Beschwörungen',E'Summons',E'invocaciones',E'Invocations',E'Evocazioni',E'Invocações'),
('5',E'Schaden',E'Damage',E'daños',E'Dommages',E'Danni',E'Danos'),
('6',E'Heilung',E'Heals',E'curas',E'Soins',E'Cure',E'Cura'),
('7',E'Initiative',E'Initiative',E'iniciativa',E'Initiative',E'Iniziativa',E'Iniciativa'),
('8',E'% KT',E'% Critical',E'% crítico',E'% Critique',E'% CC',E'% de crítico'),
('9',E'Res. gg. BP-Entzug',E'MP Parry',E'a la esquiva pérdidas de PM',E'Esquive PM',E'Schivata PM',E'Esquiva PM'),
('10',E'Res. gg. AP-Entzug',E'AP Parry',E'a la esquiva pérdidas de PA',E'Esquive PA',E'Schivata PA',E'Esquiva PA'),
('11',E'AP-Entzug',E'AP Reduction',E'al retiro de PA',E'Retrait PA',E'Sottrazione PA',E'Retirada de PA'),
('12',E'BP-Entzug',E'MP Reduction',E'al retiro de PM',E'Retrait PM',E'Sottrazione PM',E'Retirada de PM'),
('13',E'Filzpunkte',E'Prospecting',E'prospección',E'Prospection',E'Prospezione',E'Prospecção'),
('14',E'Neutralschaden',E'Neutral Damage',E'daños de neutral',E'Dommages Neutre',E'Danni Neutro',E'Danos Neutro'),
('15',E'Erdschaden',E'Earth Damage',E'daños de tierra',E'Dommages Terre',E'Danni Terra',E'Danos Terra'),
('16',E'Feuerschaden',E'Fire Damage',E'daños de fuego',E'Dommages Feu',E'Danni Fuoco',E'Danos Fogo'),
('17',E'Luftschaden',E'Air Damage',E'daños de aire',E'Dommages Air',E'Danni Aria',E'Danos Ar'),
('18',E'Wasserschaden',E'Water Damage',E'daños de agua',E'Dommages Eau',E'Danni Acqua',E'Danos Água'),
('19',E'Schubsschaden',E'Pushback Damage',E'daños por empuje',E'Dommages Poussée',E'Danni Spinta',E'Danos de Empurrão'),
('20',E'Ausweichen',E'Dodge',E'huida',E'Fuite',E'Fuga',E'Fuga'),
('21',E'Blocken',E'Lock',E'placaje',E'Tacle',E'Contrasto',E'de bloqueio'),
('22',E'Neutralresistenz',E'Neutral Resistance',E'resistencia neutral',E'Résistance Neutre',E'Resistenza Neutro',E'resistência neutra'),
('23',E'Erdresistenz',E'Earth Resistance',E'resistencia a la tierra',E'Résistance Terre',E'Resistenza Terra',E'resistência à terra'),
('24',E'Feuerresistenz',E'Fire Resistance',E'resistencia al fuego',E'Résistance Feu',E'Resistenza Fuoco',E'resistência ao fogo'),
('25',E'Wasserresistenz',E'Water Resistance',E'esistencia al agua',E'Résistance Eau',E'Resistenza Acqua',E'resistência à água'),
('26',E'Luftresistenz',E'Air Resistance',E'resistencia al aire',E'Résistance Air',E'Resistenza Aria',E'resistência ao ar'),
('27',E'Schubsresistenz',E'Pushback Resistance',E'resistencia al empuje',E'Résistance Poussée',E'Resistenza Spinta',E'Resistência ao Empurrão'),
('28',E'KT-Resistenz',E'Critical Resistance',E'resistencia a los críticos',E'Résistance Critiques',E'Resistenza Critici',E'Resistência Crítica'),
('29',E'% Neutralresistenz',E'% Neutral Resistance',E'% resistencia neutral',E'% Résistance Neutre',E'% Resistenza Neutro',E'% resistência neutra'),
('30',E'% Erdresistenz',E'% Earth Resistance',E'% resistencia tierra',E'% Résistance Terre',E'% Resistenza Terra',E'% resistência à terra'),
('31',E'% Feuerresistenz',E'% Fire Resistance',E'% resistencia al fuego',E'% Résistance Feu',E'% Resistenza Fuoco',E'% resistência ao fogo'),
('32',E'% Wasserresistenz',E'% Water Resistance',E'% resistencia al agua',E'% Résistance Eau',E'% Resistenza Acqua',E'% resistência à água'),
('33',E'% Luftresistenz',E'% Air Resistance',E'% resistencia al aire',E'% Résistance Air',E'% Resistenza Aria',E'% resistência ao ar'),
('34',E'Vitalität',E'Vitality',E'vitalidad',E'Vitalité',E'Vitalità',E'Vitalidade'),
('35',E'Stärke',E'Strength',E'fuerza',E'Force',E'Forza',E'Força'),
('36',E'Flinkheit',E'Agility',E'agilidad',E'Agilité',E'Agilità',E'Agilidade'),
('37',E'Intelligenz',E'Intelligence',E'inteligencia',E'Intelligence',E'Intelligenza',E'Inteligência'),
('38',E'Glück',E'Chance',E'suerte',E'Chance',E'Fortuna',E'Sorte'),
('39',E'Weisheit',E'Wisdom',E'sabiduría',E'Sagesse',E'Saggezza',E'Sabedoria'),
('40',E'Fallenschaden',E'Trap Damage',E'daños con trampas',E'Dommages Pièges',E'Danni Trappole',E'Danos Armadilhas'),
('41',E'Schlagkraft',E'Power',E'potencia (daños generales)',E'Puissance',E'Potenza',E'Potência'),
('42',E'(Neutralschaden)',E'(Neutral damage)',E'(neutral)',E'(dommages Neutre)',E'(danni Neutro)',E'(danos neutros)'),
('43',E'(Erdschaden)',E'(Earth damage)',E'(tierra)',E'(dommages Terre)',E'(danni Terra)',E'(danos de terra)'),
('44',E'(Feuerschaden)',E'(Fire damage)',E'(fuego)',E'(dommages Feu)',E'(danni Fuoco)',E'(danos de fogo)'),
('45',E'(Wasserschaden)',E'(Water damage)',E'(agua)',E'(dommages Eau)',E'(danni Acqua)',E'(danos de água)'),
('46',E'(Luftschaden)',E'(Air damage)',E'(aire)',E'(dommages Air)',E'(danni Aria)',E'(danos de ar)'),
('47',E'LP-Diebstahl (Neutral)',E'(Neutral steal)',E'PdV (neutral)',E'(vol Neutre)',E'(furto Neutro)',E'(roubo de neutra)'),
('48',E'LP-Diebstahl (Erde)',E'(Earth steal)',E'PdV (tierra)',E'(vol Terre)',E'(furto Terra)',E'(roubo de terra)'),
('49',E'LP-Diebstahl (Feuer)',E'(Fire steal)',E'PdV (fuego)',E'(vol Feu)',E'(furto Fuoco)',E'(roubo de fogo)'),
('50',E'LP-Diebstahl (Wasser)',E'(Water steal)',E'PdV (agua)',E'(vol Eau)',E'(furto Acqua)',E'(roubo de água)'),
('51',E'LP-Diebstahl (Luft)',E'(Air steal)',E'PdV (aire)',E'(vol Air)',E'(furto Aria)',E'(roubo de ar)'),
('52',E'(LP zurück)',E'(HP restored)',E'(PdV devueltos)',E'(PV rendus)',E'(PV restituiti)',E'(PV restaurados)'),
('53',E'KT-Schaden',E'Critical Damage',E'daños críticos',E'Dommages Critiques',E'Danni Critici',E'Danos Críticos'),
('54',E'Schlagkraft (Fallen)',E'Power (traps)',E'potencia (daños generales) con trampas',E'Puissance (pièges)',E'Potenza (trappole)',E'Potência (armadilhas)'),
('55',E'% Zauberschaden',E'% Spell Damage',E'% daños a los hechizos',E'% Dommages aux sorts',E'% Danni degli Incantesimi',E'% de danos de feitiços'),
('56',E'% Nahkampfresistenz',E'% Melee Resistance',E'% resistencia CaC',E'% Résistance mêlée',E'% Resistenza in Mischia',E'% de resistência ao corpo a corpo'),
('57',E'% Fernkampfresistenz',E'% Ranged Resistance',E'% resistencia distancia',E'% Résistance distance',E'% Resistenza a Distanza',E'% de resistência à distância'),
('58',E'% Nahkampfschaden',E'% Melee Damage',E'% daños CaC',E'% Dommages mêlée',E'% Danni da mischia',E'% de danos no corpo a corpo'),
('59',E'% Fernkampfschaden',E'% Ranged Damage',E'% daños distancia',E'% Dommages distance',E'% Danni a distanza',E'% de danos à distância'),
('60',E'% Waffenschaden',E'% Weapon Damage',E'% daños de armas',E'% Dommages d''armes',E'% Danni delle Armi',E'% de danos de armas'),
('61',E'LP',E'HP',E'PdV',E'Vie',E'Vita',E'Vida'),
('62',E'Gibt Punkte Energie zurück',E'Restores energy points',E'Devuelve puntos de energía',E'Rend points d''énergie',E'Restituisce punti energia',E'Restaura de pontos de energia'),
('63',E'Verleiht  Minuten lang einen Bonus von  % auf die Berufe.',E'Applies a % experience bonus to professions for minutes',E'Aplica un bonuns de % de experiencia en los oficios durante minutos',E'Applique un bonus de % d''expérience sur les métiers pendant minutes',E'Bonus all\'esperienza dei mestieri della durata di minuti: %',E'Aplica um bônus de % de experiência nas profissões durante minutos'),
('64',E'Verleiht  Minuten lang einen Erfahrungsbonus von  %.',E'Applies an experience bonus of % for minutes',E'Aplica un bonuns de % de experiencia durante minutos',E'Applique un bonus de % d''expérience pendant minutes',E'Bonus all\'esperienza della durata di minuti: %',E'Aplica um bônus de % de experiência por minutos'),
('65',E'Gemeinsames Herstellen nicht möglich.',E'Cooperative crafting impossible',E'Craft cooperativo imposible.',E'Craft coopératif impossible.',E'Craft cooperativo impossibile.',E'Fabricação cooperativa impossível.'),
('66', 'KT', 'CH', 'GC', 'CC', 'CC', 'GC');

INSERT INTO "public"."attribute"("isdamage","id")
VALUES
(FALSE,'1'),
(FALSE,'2'),
(FALSE,'3'),
(FALSE,'4'),
(FALSE,'5'),
(FALSE,'6'),
(FALSE,'7'),
(FALSE,'8'),
(FALSE,'9'),
(FALSE,'10'),
(FALSE,'11'),
(FALSE,'12'),
(FALSE,'13'),
(FALSE,'14'),
(FALSE,'15'),
(FALSE,'16'),
(FALSE,'17'),
(FALSE,'18'),
(FALSE,'19'),
(FALSE,'20'),
(FALSE,'21'),
(FALSE,'22'),
(FALSE,'23'),
(FALSE,'24'),
(FALSE,'25'),
(FALSE,'26'),
(FALSE,'27'),
(FALSE,'28'),
(FALSE,'29'),
(FALSE,'30'),
(FALSE,'31'),
(FALSE,'32'),
(FALSE,'33'),
(FALSE,'34'),
(FALSE,'35'),
(FALSE,'36'),
(FALSE,'37'),
(FALSE,'38'),
(FALSE,'39'),
(FALSE,'40'),
(FALSE,'41'),
(TRUE,'42'),
(TRUE,'43'),
(TRUE,'44'),
(TRUE,'45'),
(TRUE,'46'),
(TRUE,'47'),
(TRUE,'48'),
(TRUE,'49'),
(TRUE,'50'),
(TRUE,'51'),
(TRUE,'52'),
(FALSE,'53'),
(FALSE,'54'),
(FALSE,'55'),
(FALSE,'56'),
(FALSE,'57'),
(FALSE,'58'),
(FALSE,'59'),
(FALSE,'60'),
(FALSE,'61'),
(FALSE,'62'),
(FALSE,'63'),
(FALSE,'64'),
(FALSE,'65'),
(FALSE,'66');
